# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/source/en/conf.py

# 构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# 安装 Python 依赖
python:
  install:
    # ✅ 确保 requirements.txt 路径正确
    - requirements: docs/requirements.txt